on: [push]
jobs:
  mail_on_push:
    runs-on: ubuntu-latest
    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: "New Push Notification"
        body: "pranks ${{ github.event.pusher.name }} about ${{ github.repository }} with a message: '${{ github.event.head_commit.message }}'"
        to: piritamarcus@gmail.com
        from: "Github Actions"
